# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changellybinance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricedelta',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
