# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-24 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('changellybinance', '0002_pricedelta_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMCCoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmc_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('website_slug', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CoinMention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='changellybinance.CMCCoin')),
            ],
        ),
    ]
