# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changellybinance', '0003_cmccoin_coinmention'),
    ]

    operations = [
        migrations.CreateModel(
            name='BizThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('time', models.PositiveIntegerField()),
                ('number', models.PositiveIntegerField()),
                ('filename', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('subtitle', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BizThreadReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('number', models.PositiveIntegerField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
