# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changellybinance', '0004_bizthread_bizthreadreply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bizthread',
            old_name='time',
            new_name='time_int',
        ),
        migrations.RenameField(
            model_name='bizthreadreply',
            old_name='time',
            new_name='time_int',
        ),
    ]
