# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changellybinance', '0005_auto_20180625_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bizthread',
            name='subtitle',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
