# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 03:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('changellybinance', '0008_auto_20180628_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='bizcoinmention',
            name='biz_thread',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='changellybinance.BizThread'),
            preserve_default=False,
        ),
    ]
