# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changellybinance', '0010_auto_20180701_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSNotificationSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30)),
                ('delta_threshold', models.FloatField(blank=True, default=0.0)),
            ],
        ),
    ]
