# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-08 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changellybinance', '0011_smsnotificationsetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsnotificationsetting',
            name='id',
        ),
        migrations.AlterField(
            model_name='smsnotificationsetting',
            name='phone_number',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
