# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CMCCoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmc_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('website_slug', models.CharField(max_length=50)),
            ],
        ),
    ]
